
export interface Book {
    id:          number;
    title:       string;
    description: string;
    category:    string;
    thumbnail:   string;
    author:      string;
    price:       number;
    quantity:    number;
    createdAt:   string;
    updatedAt:   string;
}

// Generated by https://quicktype.io

export interface Item {
    id:          number;
    title:       string;
    description: null;
    category:    null;
    thumbnail:   string;
    author:      null;
    price:       number;
    quantity:    number;
    createdAt:   string;
    updatedAt:   string;
}

